In [3]:
import numpy as np

## Difference between a Python list and a Numpy array:
If you don't specify that you're making a Numpy array, you're making a list of lists! As in the following:

In [35]:
a = [[[1],[2],[3]], [[4],[5],[6]]]
print("as Python list a = ", a)

as Python list a =  [[[1], [2], [3]], [[4], [5], [6]]]


However, if you specify that you're making a numpy array, that's what you get!

In [36]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print("as numpy array, x = \n", x)

as numpy array, x = 
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


## What is the difference between each element [enclosed] in square brackets vs not enclosed? 
### Contrast the following cell with the cell above.

In [34]:
y = np.array([[1,2,3], [4,5,6]])
print("as numpy array, y = \n", y)

as numpy array, y = 
 [[1 2 3]
 [4 5 6]]


In [39]:
# print("Shape of 'a':", a.shape)
print("Shape of 'x':", x.shape)
print("Shape of 'y':", y.shape)

Shape of 'x': (2, 3, 1)
Shape of 'y': (2, 3)


Ah, the conclusion here is that for every layer of nested brackets, another dimension is added to the array. That's why the x array has 3 dimensions - the brackets around individual elements imply that there is a dimension into the page. In contrast to the y array, which only has width and height. 
<br/><br/> For more, see: https://stackoverflow.com/questions/39694318/difference-between-single-and-double-bracket-numpy-array for an explanation of 0D vis 1D results. 
<br/><br/>


#  
#  
#  

## Indexing Python List-of-Lists versus Numpy Arrays
>-Index **list of lists** using square brackets: **[row][column]**
<br/>
>-Index **numpy arrays** w one set of brackets and a comma **[row,column]**

In [48]:
x[0:2][1]

array([[4],
       [5],
       [6]])

The cell above gives confusing results because x is actually a list of list *of lists*. Need to reduce x to be just a list of lists.

In [14]:
x[1, 1:]

array([[5],
       [6]])

In [15]:
# Practice: print the first column of data, which should have values of 1, 4.
x[0:2,0]

array([[1],
       [4]])

In [19]:
# Same result as cell above
x[:,0]

array([[1],
       [4]])

In [20]:
# Can you select a column using two sets of square brackets? It seems like NO. But why??
x[0:2][0]

array([[1],
       [2],
       [3]])

#  
#  
#  

## Why does the code below throw an error?

In [42]:
z = [[1,2,3],[1,2,3]]
print("y[0,0] = ", y[0,0])
print("z[0,0] = ", z[0,0])    

y[0,0] =  1


TypeError: list indices must be integers or slices, not tuple

## Try to figure it out.

In [44]:
z = [[1,2,3],[1,2,3]]
print(z)

[[1, 2, 3], [1, 2, 3]]


## Ahh, notice that z is a list of lists, NOT a numpy array! 
Because I never converted z into a numpy array. That's probably why I wasn't able to call z[0,0] in order to print that element. <br/> <br/> 
I *do* wonder how I would index that list, though... 


In [50]:
z = np.array([[1,2,3],[1,2,3]])
print("y[0,0] = ", y[0,0])
print("z[0,0] = ", z[0,0])   

y[0,0] =  1
z[0,0] =  1


Ahhh nice, it works!

# Go back to the kNN implementation of the first HW
See if I can get it to work, at least partially, wrt that stubborn error about "...tuple..."

In [ ]:
# define a function to select the k rows that represent the vectors with the shortest
# distances to an inputted vector.
import operator

def getNeighbors(inputVector, inputVectorRow, int(k)):
    numRows = 100;
    
    # distancesMatrix has 3 columns: row index #, distance from input vector, label value.
    # neighborsMatrix has the same 3 columns.
    distancesMatrix = np.zeros(shape = (numRows-1, 3), dtype=float) #don't count the row against which you're comparing.
    neighborsMatrix = np.zeros(shape = (k, 3), dtype=float)
    
    for row in range(numRows): 
        if inputVectorRow != row:
            distance = sc.spatial.distance.euclidean(inputVector, attributesMatrixOriginal[row])
            distancesMatrix[row, 0] = row
            distancesMatrix[row, 1] = distance
            distancesMatrix[row, 2] = labelsMatrix[row, 0]
    distancesMatrix = sorted(distancesMatrix, key=operator.itemgetter(1))
    
    neighborsMatrix = distancesMatrix[1,1:].deepcopy()
#     neighborsMatrix = np.c_[neighborsMatrix, distancesMatrix[0,:]] 

    
#     for i in range(k):
#         neighborsMatrix[i,0] = distancesMatrix[i, 0]
#         neighborsMatrix[i,1] = distancesMatrix[i, 1]
#         neighborsMatrix[i,2] = distancesMatrix[i, 2] 
    
    return neighborsMatrix;  

print(getNeighbors(attributesMatrixOriginal[1,0:], 1, 7))

In [22]:
# Can I repeat a row-vector to make a matrix where every row equals that vector?
import numpy as np
x = np.array([[1,2,3,4]])
print(x)
print("shape of x with two sets of square brackets ", x.shape)


[[1 2 3 4]]
shape of x with two sets of square brackets  (1, 4)


In [25]:
y = np.repeat(x, 3, axis=0)
print(y)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
